DROP DATABASE IF EXISTS goalfy;

CREATE DATABASE goalfy;

USE goalfy;

CREATE TABLE clients(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fullname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
	phone VARCHAR(11) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    address VARCHAR(255) NOT NULL
);